# -*- coding: utf-8 -*-
"""HBOS_to_CWT_LSTM_to_BiLSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wX9XY2luwX-3lOwKLWzdKrB_hF5Dfzj

# **Import Dataset**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pyod
import os
import numpy as np
from pyod.models import hbos
from pyod.utils.data import evaluate_print
from sklearn.metrics import confusion_matrix,cohen_kappa_score,f1_score
from scipy import signal
import matplotlib.pyplot as plt
import pickle
import pandas as pd

df = pd.read_csv('/content/sample_data/features_raw.csv')

data=df['Fp1']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - FP1', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

'''data=df['Fp1']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt

# Example function to apply CWT on dataset
def apply_cwt(data):
    widths = np.arange(1, 31)
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Assuming you have your time series data in 'data'
cwt_transformed_data = apply_cwt(data)

# You can visualize the transformed data as a scalogram (wavelet spectrogram)
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='PRGn', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
plt.title('CWT Scalogram - FP1', fontweight='bold')
plt.show()'''
#correctcode but graph is in dim colour......

data=df['F3']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - F3', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

data=df['F7']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - F7', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

data=df['Fp2']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - FP2', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

data=df['F4']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - F4', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

data=df['F8']
# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
def apply_cwt(data):
    widths = np.arange(1, 31)  # Scale range
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Apply CWT to the data
cwt_transformed_data = apply_cwt(data)

# Plot the CWT scalogram
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='seismic', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
#plt.colorbar(label='Wavelet Coefficient')

# Set bold font for axis labels
plt.title('CWT Scalogram - F8', fontweight='bold')
#plt.xlabel('Time', fontweight='bold')
#plt.ylabel('Scale', fontweight='bold')

# Set bold font for tick labels (axis values)
plt.tick_params(axis='both', which='both', labelsize=10, width=2)  # Customize tick size
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')

plt.show()

#####
# Trial or epoch = eeg segment
#####

channels = 32
seconds = 0.5    # Size of each segment we want
fs = 256.0         # Dtaset eeg sampling rate
data_portion = 1
save_model = False

df = pd.read_csv('/content/sample_data/features_raw.csv')
df.head()

import matplotlib.pyplot as plt

# Create subplots: 6 rows, 1 column
fig, axs = plt.subplots(6, 1, figsize=(10, 12))

# Plot each signal on a separate subplot and add titles for Normal and Depressed
axs[0].plot(df['Fp2'])
axs[0].set_title('Fp2 (Normal)')

axs[1].plot(df['F4'])
axs[1].set_title('F4 (Normal)')

axs[2].plot(df['F8'])
axs[2].set_title('F8 (Normal)')

axs[3].plot(df['Fp1'])
axs[3].set_title('Fp1 (Depressed)')

axs[4].plot(df['F3'])
axs[4].set_title('F3 (Depressed)')

axs[5].plot(df['F7'])
axs[5].set_title('F7 (Depressed)')

# Add common labels
plt.xlabel('Time')
plt.ylabel('Amplitude')

# Adjust layout for better spacing
plt.tight_layout()

# Show plot
plt.show()

import matplotlib.pyplot as plt

# Create subplots: 6 rows, 1 column
fig, axs = plt.subplots(6, 1, figsize=(8, 10))

# Define colors for each plot
colors = ['b', 'g', 'r', 'c', 'm', 'y']  # Blue, Green, Red, Cyan, Magenta, Yellow

# Plot each signal on a separate subplot with different colors and add titles for Normal and Depressed
axs[0].plot(df['Fp2'], color=colors[0])
axs[0].set_title('Fp2 (Normal)')

axs[1].plot(df['F4'], color=colors[1])
axs[1].set_title('F4 (Normal)')

axs[2].plot(df['F8'], color=colors[2])
axs[2].set_title('F8 (Normal)')

axs[3].plot(df['Fp1'], color=colors[3])
axs[3].set_title('Fp1 (Depressed)')

axs[4].plot(df['F3'], color=colors[4])
axs[4].set_title('F3 (Depressed)')

axs[5].plot(df['F7'], color=colors[5])
axs[5].set_title('F7 (Depressed)')

# Add common labels
plt.xlabel('Time')
plt.ylabel('Amplitude')

# Adjust layout for better spacing
plt.tight_layout()

# Show plot
plt.show()

plt.plot(df['Fp2'])

plt.plot(df['AF3'])

plt.plot(df['F3'])

class EEGDataset2:
    def __init__(self, train_csv, seconds=0.500, fs=256, data_portion=1, normalize=True, isolated_channels=False):
        assert data_portion > 0.0 and data_portion <= 1, 'data_portion should be > 0 and <= 1'

        self.isolated_channels = isolated_channels
        self.normalize = normalize
        self.train_csv = train_csv
        self.seconds = seconds
        self.fs = fs
        self.data_portion = data_portion

    def get_data(self):
        df = pd.read_csv(self.train_csv)
        array_size = int(self.seconds * self.fs)
        # Dataset shape is: [data x channels]
        # we want shape: [segments x features]

        if self.normalize:
            df = (df - df.mean()) / df.std()

        if self.isolated_channels:
            channels = []
            for channel in df.columns[0:32]:
                isolated_channel = []
                for i in range(int(len(df) / array_size)):
                    isolated_channel.append(df[channel][i*array_size:(i+1)*array_size].to_numpy())
                channels.append(np.array(isolated_channel))
            return np.array(channels)

        dataset = []

        for channel in df.columns[0:32]:
            for i in range(int(len(df) / array_size)):
                dataset.append(df[channel][i*array_size:(i+1)*array_size].to_numpy())

        return np.array(dataset)

train_csv = '/content/sample_data/features_raw.csv'
eegDataset = EEGDataset2(train_csv, seconds, fs, data_portion, normalize=True)

train_dataset = eegDataset.get_data()

train_dataset.shape

# Import required libraries for Continuous Wavelet Transform (CWT)
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt

# Example function to apply CWT on dataset
def apply_cwt(data):
    widths = np.arange(1, 31)
    cwt_matrix = signal.cwt(data, signal.ricker, widths)
    return cwt_matrix

# Assuming you have your time series data in 'data'
cwt_transformed_data = apply_cwt(data)

# You can visualize the transformed data as a scalogram (wavelet spectrogram)
plt.imshow(cwt_transformed_data, extent=[0, 1, 1, 31], cmap='PRGn', aspect='auto',
           vmax=abs(cwt_transformed_data).max(), vmin=-abs(cwt_transformed_data).max())
plt.title('CWT Scalogram')
plt.show()

# Import the necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

# Assuming you have your features and labels ready
# Replace 'features' and 'labels' with your actual data
features = train_dataset  # Use your existing train_dataset

# Define your labels - This is just an example, replace with your actual labels!
# Ensure that the number of labels matches the number of samples in your features
labels = np.random.randint(0, 2, size=len(features))

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

# Create a classifier object (e.g., RandomForestClassifier)
clf = RandomForestClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Now you can use clf for predictions
pred = clf.predict(train_dataset)

# ... rest of your code for plotting

for i in range(len(pred)):
    plt.rcParams["figure.figsize"] = (20,8)

    if pred[i] == 1: plt.plot(range(128*i,128*(i+1)), train_dataset[i], color='red')
    else: plt.plot(range(128*i,128*(i+1)), train_dataset[i], color='b')
plt.title("train_dataset")
plt.show() # Add this line to display the plot

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import tensorflow
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import SGD

from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
tf.keras.backend.clear_session()

# Instead of importing plot_confusion_matrix, import ConfusionMatrixDisplay
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn import datasets, tree, linear_model, svm
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import confusion_matrix,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

import seaborn as sns
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

#Reading dataset
data = pd.read_csv("/content/sample_data/emotions.csv")

#chceking length of dataset
len(data)

#Seprarting Positive,Neagtive and Neutral dataframes for plortting
pos = data.loc[data["label"]=="POSITIVE"]
sample_pos = pos.loc[2, 'fft_0_b':'fft_749_b']
neg = data.loc[data["label"]=="NEGATIVE"]
sample_neg = neg.loc[0, 'fft_0_b':'fft_749_b']
neu = data.loc[data["label"]=="NEUTRAL"]
sample_neu = neu.loc[1, 'fft_0_b':'fft_749_b']

'''#plottintg Dataframe distribution
plt.figure(figsize=(25,7))
plt.title("Data distribution of Emotions")
plt.style.use('fivethirtyeight')
sns.countplot(x='label', data=data)
plt.show()'''

# Plotting DataFrame distribution with a custom color palette
plt.figure(figsize=(25,7))
plt.title("Data distribution of Emotions")
plt.style.use('fivethirtyeight')

# Use a custom color palette
custom_colors = sns.color_palette("Set2")  # You can change this to another palette like "Set1", "Paired", etc.
sns.countplot(x='label', data=data, palette=custom_colors)

plt.show()

#Plotting Positive DataFrame
plt.figure(figsize=(16, 10))
plt.plot(range(len(sample_pos)), sample_pos)
#plt.title("Graph of Positive Columns")
plt.title("Graph of Normal Level")
plt.show()
'''As we can noticed the most of the Negative Signals are from greater than 600 to and less than than -600'''

#Plotting Negative DataFrame
plt.figure(figsize=(16, 10))
plt.plot(range(len(sample_neg)), sample_neg)
#plt.title("Graph of Negative Columns")
plt.title("Graph of Severe level")
plt.show()
'''As we can noticed the most of the Negative Signals are from less than 600 to and greater than -600'''

#Plotting Neutral DataFrame
plt.figure(figsize=(16, 10))
plt.plot(range(len(sample_neu)), sample_neu)
#plt.title("Graph of Neutral Columns")
plt.title("Graph of Mild level")
plt.show()
'''As we can see the most of the Neutral Signals ae in between -50 to 250 '''

def Transform_data(data):
    #Encoding Lables into numbers
    encoding_data = ({'NEUTRAL': 0, 'POSITIVE': 1, 'NEGATIVE': 2} )
    data_encoded = data.replace(encoding_data)
    #getting brain signals into x variable
    x=data_encoded.drop(["label"]  ,axis=1)
    #getting labels into y variable
    y = data_encoded.loc[:,'label'].values
    scaler = StandardScaler()
    #scaling Brain Signals
    scaler.fit(x)
    X = scaler.transform(x)
    #One hot encoding Labels
    Y = to_categorical(y)
    return X,Y

#Calling above function and splitting dataset into train and test
X,Y = Transform_data(data)
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

#checking shape of dataset
x_train.shape[1]

def create_model():
    # Input layer of model for brain signals
    inputs = tf.keras.Input(shape=(x_train.shape[1],))

    # Hidden Layer for Brain signal using Bidirectional LSTM
    # Use Keras Lambda layer to wrap tf.expand_dims to add a third dimension
    expand_dims = tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=2))(inputs)

    # Bidirectional LSTM layer with 256 units
    bilstm = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(256, return_sequences=True))(expand_dims)

    # Flatten the BiLSTM layer into vector form (one-dimensional array)
    flatten = tf.keras.layers.Flatten()(bilstm)

    # Output layer of the model
    outputs = tf.keras.layers.Dense(3, activation='softmax')(flatten)

    # Create the model
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    # Print the model summary
    print(model.summary())

    return model

# Creating the BiLSTM model
bilstm_model = create_model()

# Compiling the model
bilstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

#Training and Evaluting model
history = bilstm_model.fit(x_train, y_train, epochs = 10, validation_split=0.1)
loss, acc = bilstm_model.evaluate(x_test, y_test)

tf.keras.utils.plot_model(bilstm_model, to_file='BiLSTM-model.png', show_shapes=True)

#Loss and Accuracy of model on Testiong Dataset
print(f"Loss on testing: {loss*100}",f"\nAccuracy on Training: {acc*100}")

#predicting model on test set for plotting Confusion Matrix
pred  = bilstm_model.predict(x_test)

#Creation of Function of Confusion Matrix
def plot_confusion_matrix(cm, names, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(data.label.unique()))
    plt.xticks(tick_marks, names, rotation=90)
    plt.yticks(tick_marks, names)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

#after getting prediction checking maximum score prediction to claim which emotion this brain signal belongs to
pred1 = np.argmax(pred,axis=1)

#inversing the one hot encoding
y_test1 =   np.argmax(y_test,axis=1)

#printing first 10 Actual and predicted outputs of Test brain signals
print("Predicted:  ",pred1[:10])
print("\n")
print("Actual: ",y_test1[:10])

#Plotting Confusion matrix of BiLstm Model
cm = confusion_matrix(y_test1, pred1)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.rcParams["figure.figsize"]=(20,5)
plt.figure()
plot_confusion_matrix(cm,["Neutral","Positive","Negative"])

names1 = ["Neutral","Positive","Negative"]

!pip install -U scikit-learn
#Importing all the required libraries
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

#Training our dataset on different Classifiers to check the results and creating their classification reports
#NAves Bayes Clssifier
Classifier_gnb = GaussianNB().fit(x_train, np.argmax(y_train,axis=1))
pred_gnb = Classifier_gnb.predict(x_test)
print ('\n*\t\tClassification Report GNB:\n', classification_report(np.argmax(y_test,axis=1), pred_gnb))
confusion_matrix_graph = confusion_matrix(np.argmax(y_test,axis=1), pred_gnb)
### Support Vector Machine

Classifier_svm = svm.SVC(kernel='linear').fit(x_train, np.argmax(y_train,axis=1))
pred_svm = Classifier_svm.predict(x_test)
print ('\n*\t\tClassification Report SVM:\n', classification_report(np.argmax(y_test,axis=1), pred_svm))
confusion_matrix_graph = confusion_matrix(np.argmax(y_test,axis=1), pred_svm)
### Logistic Regression

Classifier_LR = linear_model.LogisticRegression(solver = 'liblinear', C = 75).fit(x_train, np.argmax(y_train,axis=1))
pred_LR = Classifier_LR.predict(x_test)
print ('\n*\t\tClassification Report LR:\n', classification_report(np.argmax(y_test,axis=1), pred_LR))
confusion_matrix_graph = confusion_matrix(np.argmax(y_test,axis=1), pred_LR)
### Decision Tree Regressor

Classifier_dt = tree.DecisionTreeClassifier().fit(x_train, np.argmax(y_train,axis=1))
pred_dt = Classifier_dt.predict(x_test)
print ('\n*\t\tClassification Report Deccsion Tree:\n', classification_report(np.argmax(y_test,axis=1), pred_dt))
confusion_matrix_graph = confusion_matrix(np.argmax(y_test,axis=1), pred_dt)
### Random Forest

Classifier_forest = RandomForestClassifier(n_estimators = 50, random_state = 0).fit(x_train,np.argmax(y_train,axis=1))
pred_fr = Classifier_dt.predict(x_test)


print ('\n*\t\tClassification Report Random Forest:\n', classification_report(np.argmax(y_test,axis=1), pred_fr))
confusion_matrix_graph = confusion_matrix(np.argmax(y_test,axis=1), pred_fr)
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(15,10))
classifiers = [GaussianNB(),svm.SVC(kernel='linear'),
               linear_model.LogisticRegression(solver = 'liblinear', C = 75),
               RandomForestClassifier(n_estimators = 50, random_state = 0)]

for cls in classifiers:
    cls.fit(x_train,np.argmax(y_train,axis=1))

colors = [ 'YlOrBr', 'GnBu', 'Pastel2', 'PuRd']
for cls, ax,c in zip(classifiers, axes.flatten(),colors):
    cm = confusion_matrix(np.argmax(y_test,axis=1), cls.predict(x_test)) #Calculate the confusion matrix for the classifier
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(ax=ax, cmap=c)
plt.tight_layout()
plt.show()

#Classification Report of BiLstm model
from sklearn.metrics import accuracy_score # import the function
print('\n*\t\tClassification Report OF Brain Waves Bidirectional(BiLSTM:\n', classification_report(np.argmax(y_test,axis=1), np.argmax(bilstm_model.predict(x_test),axis=1) ))

Accuracy_ban=accuracy_score(np.argmax(y_test,axis=1), np.argmax(bilstm_model.predict(x_test),axis=1))
Accuracy_ban*100

print ('\n*\t\tAccuracy GNB:\n', accuracy_score(np.argmax(y_test,axis=1), pred_gnb))
print ('\n*\t\tAccuracy LR:\n',accuracy_score(np.argmax(y_test,axis=1), pred_LR))
print ('\n*\t\tAccuracy SVM:\n', accuracy_score(np.argmax(y_test,axis=1), pred_svm))
print ('\n*\t\t Accuracy DT:\n', accuracy_score(np.argmax(y_test,axis=1), pred_dt))
print ('\n*\t\tAccuracy Random Forest:\n',  accuracy_score(np.argmax(y_test,axis=1), pred_fr))

#Plotting Graph of Lstm model Training, Loss and Accuracy
plt.style.use("fivethirtyeight")
plt.figure(figsize = (20,6))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("NeuroWave-BiLSTM Model-Loss",fontsize=20)
plt.ylabel('Loss')
plt.xlabel('Epochs')
plt.legend(['train loss', 'validation loss'], loc ='best')

plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("NeuroWave-BiLSTM Model-Accuracy",fontsize=20)
plt.ylabel('Accuracy')
plt.xlabel('Epochs')
plt.legend(['training accuracy', 'validation accuracy'], loc ='best')
plt.show()

"""**Below code:**
Purpose: The code generates three different loss landscapes representing various stages of BiLSTM model training on Continuous Wavelet Transform (CWT) features.
Flat Loss Landscape: Represents the initial stage with no learning.
Sinusoidal Loss Landscape: Represents the middle stage where the model starts learning from complex patterns.
Cosine Loss Landscape: Represents a more advanced stage of training, capturing both long-term and short-term dependencies..
This type of visualization can help understand how the model's loss changes during training.
"""

import numpy as np
import matplotlib.pyplot as plt

# Generate data for the three subplots representing loss landscapes
x = np.linspace(0, 10, 100)

# Subplot (a): Flat loss landscape
y_flat = np.ones_like(x)

# Subplot (b): Sinusoidal loss landscape
y_sinusoidal = np.sin(x)

# Subplot (c): Cosine loss landscape
y_cosine = np.cos(x)

# Create subplots (3 rows, 1 column for vertical arrangement)
fig, axs = plt.subplots(3, 1, figsize=(8, 12))

# Subplot (a)
axs[0].plot(x, y_flat, color='blue')
axs[0].set_title("Initial Flat Loss Landscape: Early Stage of BiLSTM Training on CWT Features")
axs[0].set_xlabel("Training Steps")
axs[0].set_ylabel("Loss")

# Subplot (b)
axs[1].plot(x, y_sinusoidal, color='green')
axs[1].set_title("Sinusoidal Loss Landscape: Navigating Complex Time-Frequency Dependencies")
axs[1].set_xlabel("Training Steps")
axs[1].set_ylabel("Loss")

# Subplot (c)
axs[2].plot(x, y_cosine, color='red')
axs[2].set_title("Cosine Loss Landscape: Learning Long and Short-Term Dependencies in CWT")
axs[2].set_xlabel("Training Steps")
axs[2].set_ylabel("Loss")

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Function to generate a sinusoidal surface (representing one optimization landscape)
def sin_surface(X, Y):
    return np.sin(np.sqrt(X**2 + Y**2))

# Function to generate a cosine surface (representing another optimization landscape)
def cos_surface(X, Y):
    return np.cos(np.sqrt(X**2 + Y**2))

# Generate a grid of x and y values
x = np.linspace(-5, 5, 50)
y = np.linspace(-5, 5, 50)
X, Y = np.meshgrid(x, y)

# Compute the corresponding Z values for the surfaces
Z_sin = sin_surface(X, Y)
Z_cos = cos_surface(X, Y)

# Points representing the start (red) and end (purple) of the optimization path
start_point = np.array([1, 1])
end_point = np.array([3, 3])

# Create a figure with subplots arranged vertically
fig = plt.figure(figsize=(8, 15))

# Plot (a): Flat surface with two points connected by a dashed line
ax1 = fig.add_subplot(311, projection='3d')
ax1.scatter(start_point[0], start_point[1], 0, color='red', s=100, label='Start')
ax1.scatter(end_point[0], end_point[1], 0, color='purple', s=100, label='End')
ax1.plot([start_point[0], end_point[0]], [start_point[1], end_point[1]], [0, 0], 'k--')
ax1.set_title('Initial Flat Loss Landscape: Early Stage of BiLSTM Training with CWT Features')
ax1.set_zlim(0, 1)
ax1.legend()

# Plot (b): 3D Sin surface with two points connected by a dashed line
ax2 = fig.add_subplot(312, projection='3d')
ax2.plot_surface(X, Y, Z_sin, cmap='viridis', alpha=0.6, edgecolor='none')
ax2.scatter(start_point[0], start_point[1], sin_surface(start_point[0], start_point[1]), color='red', s=100)
ax2.scatter(end_point[0], end_point[1], sin_surface(end_point[0], end_point[1]), color='purple', s=100)
ax2.plot([start_point[0], end_point[0]], [start_point[1], end_point[1]],
         [sin_surface(start_point[0], start_point[1]), sin_surface(end_point[0], end_point[1])], 'k--')
ax2.set_title('Sinusoidal Loss Landscape: Complex Temporal Pattern Learning in BiLSTM')

# Plot (c): 3D Cos surface with two points connected by a dashed line
ax3 = fig.add_subplot(313, projection='3d')
ax3.plot_surface(X, Y, Z_cos, cmap='viridis', alpha=0.6, edgecolor='none')
ax3.scatter(start_point[0], start_point[1], cos_surface(start_point[0], start_point[1]), color='red', s=100)
ax3.scatter(end_point[0], end_point[1], cos_surface(end_point[0], end_point[1]), color='purple', s=100)
ax3.plot([start_point[0], end_point[0]], [start_point[1], end_point[1]],
         [cos_surface(start_point[0], start_point[1]), cos_surface(end_point[0], end_point[1])], 'k--')
ax3.set_title('Cosine Loss Landscape: Capturing Long-Term and Short-Term Dependencies in CWT-BiLSTM')

# Show the plots
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Define the confusion matrix data
data = {
    'Actual': ['SEVERE', 'MILD', 'NORMAL'],
    'SEVERE': [466, 0, 88],
    'MILD': [1, 463, 2],
    'NORMAL': [5, 14, 382]
}

# Create a DataFrame from the data
df = pd.DataFrame(data)
df.set_index('Actual', inplace=True)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(df, annot=True, fmt="d", cmap="Blues", xticklabels=df.columns, yticklabels=df.index)
plt.title('Confusion Matrix-Training ')
plt.xlabel('Predicted Labels')
plt.ylabel('Actual Labels')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Define the confusion matrix data with rates
data_rates = {
    'Actual': ['SEVERE', 'MILD', 'NORMAL'],
    'SEVERE': [0.987, 0.002, 0.011],
    'MILD': [0.000, 0.971, 0.029],
    'NORMAL': [0.186, 0.004, 0.809]
}

# Create a DataFrame from the data
df_rates = pd.DataFrame(data_rates)
df_rates.set_index('Actual', inplace=True)

# Plot the confusion matrix with rates
plt.figure(figsize=(8, 6))
sns.heatmap(df_rates, annot=True, fmt=".3f", cmap="Blues", xticklabels=df_rates.columns, yticklabels=df_rates.index)
plt.title('Confusion Matrix (Rates)-Training')
plt.xlabel('Predicted Labels')
plt.ylabel('Actual Labels')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Define the confusion matrix data with counts
data_counts = {
    'Actual': ['SEVERE', 'MILD', 'NORMAL'],
    'SEVERE': [232, 0, 43],
    'MILD': [1, 231, 7],
    'NORMAL': [3, 8, 186]
}

# Create a DataFrame from the data
df_counts = pd.DataFrame(data_counts)
df_counts.set_index('Actual', inplace=True)

# Plot the confusion matrix with counts
plt.figure(figsize=(8, 6))
sns.heatmap(df_counts, annot=True, fmt="d", cmap="Blues", xticklabels=df_counts.columns, yticklabels=df_counts.index)
plt.title('Confusion Matrix -Validation')
plt.xlabel('Predicted Labels')
plt.ylabel('Actual Labels')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Define the confusion matrix data with rates
data_rates = {
    'Actual': ['SEVERE', 'MILD', 'NORMAL'],
    'SEVERE': [0.983, 0.004, 0.013],
    'MILD': [0.000, 0.967, 0.033],
    'NORMAL': [0.182, 0.030, 0.788]
}

# Create a DataFrame from the data
df_rates = pd.DataFrame(data_rates)
df_rates.set_index('Actual', inplace=True)

# Plot the confusion matrix with rates
plt.figure(figsize=(8, 6))
sns.heatmap(df_rates, annot=True, fmt=".3f", cmap="Blues", xticklabels=df_rates.columns, yticklabels=df_rates.index)
plt.title('Confusion Matrix (Rates)-Validation')
plt.xlabel('Predicted Labels')
plt.ylabel('Actual Labels')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

fig=plt.figure(figsize=(12,7))

def addlabels(x,y):
    for i in range(len(x)):
        plt.text(i,y[i],y[i],ha='center',fontweight='bold',fontsize=15)

if __name__ == '__main__':
   x = ["GNB","LR","DT","SVM","BiLSTM+CWT"]
   y = [75.10,91.33,94.84,95.78,97.18]
palette=sns.color_palette("deep")
plt.bar(x, y,color=palette, width=0.5, zorder=3)
addlabels(x, y)

#plt.grid(color='grey',linestyle='--',linewidth=0.5)
#plt.grid(zorder=0)
#plt.grid(b=True, which='major', color='grey', linewidth=0.5,axis='both')
#plt.grid(b=True, which='minor', color='grey', linestyle=':', linewidth=0.5, axis='both')
#plt.minorticks_on()

plt.title("Accuracy ",fontweight='bold',fontsize=18)
plt.xlabel("Classification Methods",fontweight='bold',fontsize=17)
plt.ylabel("Performance in %",fontweight='bold',fontsize=17)
plt.xticks(np.arange(5), x,fontsize=15, weight='bold')
plt.yticks(fontsize=15)
plt.ylim(0,100)

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

fig=plt.figure(figsize=(12,7))

def addlabels(x,y):
    for i in range(len(x)):
        plt.text(i,y[i],y[i],ha='center',fontweight='bold',fontsize=15)
#Deep learning comparison
if __name__ == '__main__':
   x = ["LSTM","CNN","DNN","DBN","BiLSTM+CWT"]
   y = [85.29,90.53,91.74,93.09,97.18]
palette=sns.color_palette("deep")
plt.bar(x, y,color=palette, width=0.5, zorder=3)
addlabels(x, y)

#plt.grid(color='grey',linestyle='--',linewidth=0.5)
#plt.grid(zorder=0)
#plt.grid(b=True, which='major', color='grey', linewidth=0.5,axis='both')
#plt.grid(b=True, which='minor', color='grey', linestyle=':', linewidth=0.5, axis='both')
#plt.minorticks_on()

plt.title("Accuracy ",fontweight='bold',fontsize=18)
plt.xlabel("Classification Methods",fontweight='bold',fontsize=17)
plt.ylabel("Performance in %",fontweight='bold',fontsize=17)
plt.xticks(np.arange(5), x,fontsize=15, weight='bold')
plt.yticks(fontsize=15)
plt.ylim(0,100)

plt.show()

import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

n_groups = 3

index = np.arange(n_groups)
bar_width = 0.35


fontsize2use = 10

fig = plt.figure(figsize=(14,8))

Severe =[99.05,95.05,97.26]
Mild =[81.25,97.35,86.75]
Normal =[97.36,81.56,88.54]


width =0.18
plt.bar(np.arange(len(Severe)), Severe, width=width,color='#DBB40C', label = 'Severe (0)',edgecolor="w")
plt.bar(np.arange(len(Mild))+ width, Mild,color='green', width=width , label='Mild (1)',edgecolor="w")
plt.bar(np.arange(len(Normal))+ width + width, Normal, width=width , color='darkred', label = 'Normal (2)',edgecolor="w")
#plt.bar(np.arange(len(ACNN))+ width + width + width, ACNN, width=width , color='darkred', label = 'SVM',edgecolor="w")
#plt.bar(np.arange(len(CNNIEHO))+ width + width + width + width, CNNIEHO, width=width , color='darkviolet', label = 'R-CNN-LSTM',edgecolor="w")

plt.xlabel('Cognitive Level',fontsize=22,fontweight='bold',fontname='Times New Roman')
plt.ylabel('Analysis in % ',fontsize=22,fontweight='bold',fontname='Times New Roman')
plt.yticks(fontsize=19,fontname='Times New Roman')
# The number of labels should match the number of groups
plt.xticks(index + bar_width,('Severe (0)', 'Mild (1)', 'Normal (2)'),fontsize=1,fontweight='bold')
plt.legend(loc="upper right",fontsize=14,ncol=4)
plt.ylim(0, 130)
axes = plt.gca()
axes.spines['right'].set_linewidth(3)
axes.spines['top'].set_linewidth(3)
axes.spines['left'].set_linewidth(3)
axes.spines['bottom'].set_linewidth(3)
plt.title('Classification Report for NeuroWave-BiLSTM ',fontweight='bold',fontsize=20,fontname='Times New Roman')

plt.show()

import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

n_groups = 3
index = np.arange(n_groups)
bar_width = 0.35
fontsize2use = 10

fig = plt.figure(figsize=(14,8))

Severe =[99.05,95.05,97.26]
Mild =[81.25,97.35,86.75]
Normal =[97.36,81.56,88.54]

width = 0.18

# Plotting the bars
bars_severe = plt.bar(np.arange(len(Severe)), Severe, width=width, color='#DBB40C', label='Severe level', edgecolor="w")
bars_mild = plt.bar(np.arange(len(Mild)) + width, Mild, color='green', width=width, label='Mild level', edgecolor="w")
bars_normal = plt.bar(np.arange(len(Normal)) + 2 * width, Normal, width=width, color='darkred', label='Normal level', edgecolor="w")

# Adding percentage labels on top of each bar
for bar in bars_severe:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 2, f'{yval:.2f}%', ha='center', fontsize=13, fontweight='bold')

for bar in bars_mild:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 2, f'{yval:.2f}%', ha='center', fontsize=13, fontweight='bold')

for bar in bars_normal:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 2, f'{yval:.2f}%', ha='center', fontsize=13, fontweight='bold')

# Axis labels and formatting
plt.xlabel('Cognitive Level', fontsize=20, fontweight='bold', fontname='Times New Roman')
plt.ylabel('Performance in %', fontsize=20, fontweight='bold', fontname='Times New Roman')
plt.yticks(fontsize=19, fontname='Times New Roman')

# Adjust x-tick labels
plt.xticks(index + bar_width, ('Severe', 'Mild', 'Normal'), fontsize=17, fontweight='bold')

# Legend and plot details
plt.legend(loc="upper right", fontsize=14, ncol=4)
plt.ylim(0, 130)

axes = plt.gca()
axes.spines['right'].set_linewidth(3)
axes.spines['top'].set_linewidth(3)
axes.spines['left'].set_linewidth(3)
axes.spines['bottom'].set_linewidth(3)

plt.title('Classification Report for NeuroWave-BiLSTM', fontweight='bold', fontsize=19, fontname='Times New Roman')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data from the table
electrode_pairs = ['Fp1 By C3', 'F8 By C3', 'F3 By C3', 'F7 By C3', 'Fp2 By C3', 'F4 By C3']
slopes = [-0.35035, -0.75582, 0.248736, -1.41654, 0.433678, 1.01935]

# Separate positive and negative slopes
positive_slopes = [slope if slope > 0 else np.nan for slope in slopes]
negative_slopes = [slope if slope < 0 else np.nan for slope in slopes]

# Set up the figure and axis
fig, ax = plt.subplots(figsize=(8, 5))

# Plot positive and negative slopes
ax.bar(electrode_pairs, positive_slopes, color='green', label='Positive Slopes')
ax.bar(electrode_pairs, negative_slopes, color='red', label='Negative Slopes')

# Add labels and title
ax.set_xlabel('Electrode Pairs')
ax.set_ylabel('Slope')
ax.set_title('Positive and Negative Slopes for EEG Electrode Pairs')
ax.legend()

# Rotate x labels for better readability
plt.xticks(rotation=45)
plt.tight_layout()

# Show the plot
plt.show()